### ISSUE TITLE
`llm chat` errors on followup since 0.6

### ISSUE THREAD

**Issue by yorickvP** [simonw/llm-claude-3#21]
```
$ llm chat
> hello
how are you?
> not much, how are you?
Traceback (most recent call last):
  File "/nix/store/bhbq5lpdd2ncpn7b12w8d5sl6x9xm4gy-python3.12-llm-0.17/bin/.llm-wrapped", line 9, in <module>
    sys.exit(cli())
             ^^^^^
  File "/nix/store/c2d99rarg0lj5lacxghi4xwxfas6w8vf-python3-3.12.4-env/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c2d99rarg0lj5lacxghi4xwxfas6w8vf-python3-3.12.4-env/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/nix/store/c2d99rarg0lj5lacxghi4xwxfas6w8vf-python3-3.12.4-env/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c2d99rarg0lj5lacxghi4xwxfas6w8vf-python3-3.12.4-env/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c2d99rarg0lj5lacxghi4xwxfas6w8vf-python3-3.12.4-env/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c2d99rarg0lj5lacxghi4xwxfas6w8vf-python3-3.12.4-env/lib/python3.12/site-packages/llm/cli.py", line 535, in chat
    for chunk in response:
  File "/nix/store/c2d99rarg0lj5lacxghi4xwxfas6w8vf-python3-3.12.4-env/lib/python3.12/site-packages/llm/models.py", line 169, in __iter__
    for chunk in self.model.execute(
  File "/nix/store/c2d99rarg0lj5lacxghi4xwxfas6w8vf-python3-3.12.4-env/lib/python3.12/site-packages/llm_claude_3.py", line 159, in execute
    "messages": self.build_messages(prompt, conversation),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/c2d99rarg0lj5lacxghi4xwxfas6w8vf-python3-3.12.4-env/lib/python3.12/site-packages/llm_claude_3.py", line 110, in build_messages
    if response.attachments:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Response' object has no attribute 'attachments'
```

**Comment by simonw** [comment]
Thanks - this is a bug in LLM core, moving it there.
