### ISSUE TITLE
cannot import name "field validator"

### ISSUE THREAD

**Issue by xezpeleta** [simonw/llm-claude-3#4]
Hello,

After installing llm-claude-3, i get the following error when I run llm:

```
Traceback (most recent call last):
  File "/home/<redacted>/.local/bin/llm", line 5, in <module>
    from llm.cli import cli
  File "/home/<redacted>/.local/lib/python3.10/site-packages/llm/__init__.py", line 18, in <module>
    from .plugins import pm
  File "/home/<redacted>/.local/lib/python3.10/site-packages/llm/plugins.py", line 17, in <module>
    pm.load_setuptools_entrypoints("llm")
  File "/usr/lib/python3/dist-packages/pluggy/manager.py", line 297, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/<redacted>/.local/lib/python3.10/site-packages/llm_claude/__init__.py", line 6, in <module>
    from pydantic import Field, field_validator
ImportError: cannot import name 'field_validator' from 'pydantic' (/home/<redacted>/.local/lib/python3.10/site-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)

```

I'm running `llm` in my Ubuntu 20.04 (Python 3.10.12 / Pydantic 1.10.9)

Thanks!!!

**Comment by xezpeleta** [comment]
Upgraded `pydantic` to 2.x fixed the issue. Thanks
